"""added captain option to player

Revision ID: 5301e2737dd0
Revises: 3d1c7820c32c
Create Date: 2021-03-26 01:44:27.734492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5301e2737dd0'
down_revision = '3d1c7820c32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('captain', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_player_captain'), 'player', ['captain'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_captain'), table_name='player')
    op.drop_column('player', 'captain')
    # ### end Alembic commands ###
