"""added foreign keys to models

Revision ID: 17970bcb3ad4
Revises: 
Create Date: 2020-08-02 01:43:17.820937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17970bcb3ad4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_captain', table_name='game')
    op.drop_column('game', 'winner_score')
    op.drop_column('game', 'loser_score')
    op.drop_column('game', 'captain')
    op.drop_column('game', 'game_won')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('game_won', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('captain', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('loser_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('winner_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_game_captain', 'game', ['captain'], unique=False)
    # ### end Alembic commands ###
