"""added an opponent team to game entries

Revision ID: 4222b1acafe4
Revises: f787674389f9
Create Date: 2021-03-28 14:33:22.901305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4222b1acafe4'
down_revision = 'f787674389f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('opponent_team_id', sa.Integer(), nullable=True))
    op.drop_constraint('game_ibfk_1', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'team', ['opponent_team_id'], ['id'])
    op.drop_column('game', 'opponent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('opponent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_ibfk_1', 'game', 'player', ['opponent_id'], ['id'])
    op.drop_column('game', 'opponent_team_id')
    # ### end Alembic commands ###
