"""created teams table

Revision ID: 465ff8ec1f02
Revises: 0c057ce38e87
Create Date: 2021-03-24 01:03:34.096389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '465ff8ec1f02'
down_revision = '0c057ce38e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abbreviation', sa.String(length=45), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_team_abbreviation'), 'team', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.drop_index('id', table_name='game_log')
    op.drop_index('ix_game_log_created_at', table_name='game_log')
    op.drop_table('game_log')
    op.add_column('player', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_player_team_id'), 'player', ['team_id'], unique=False)
    op.create_foreign_key(None, 'player', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_index(op.f('ix_player_team_id'), table_name='player')
    op.drop_column('player', 'team_id')
    op.create_table('game_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('winner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('loser_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('winning_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('losing_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['player.id'], name='game_log_ibfk_1'),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], name='game_log_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_game_log_created_at', 'game_log', ['created_at'], unique=False)
    op.create_index('id', 'game_log', ['id'], unique=True)
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_abbreviation'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
