"""changed default values for booleans

Revision ID: 959aef2eba67
Revises: 
Create Date: 2020-08-01 22:56:11.760667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959aef2eba67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('singles', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('outs', sa.Integer(), nullable=True),
    sa.Column('base_on_balls', sa.Integer(), nullable=True),
    sa.Column('hit_by_pitch', sa.Integer(), nullable=True),
    sa.Column('runs_batted_in', sa.Integer(), nullable=True),
    sa.Column('error', sa.Integer(), nullable=True),
    sa.Column('stolen_bases', sa.Integer(), nullable=True),
    sa.Column('caught_stealing', sa.Integer(), nullable=True),
    sa.Column('innings_pitched', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('pitching_strikeouts', sa.Integer(), nullable=True),
    sa.Column('pitching_base_on_balls', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('blown_saves', sa.Integer(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('captain', sa.Boolean(), nullable=True),
    sa.Column('game_won', sa.Boolean(), nullable=True),
    sa.Column('selected_opponent', sa.Integer(), nullable=True),
    sa.Column('winner_score', sa.Integer(), nullable=True),
    sa.Column('loser_score', sa.Integer(), nullable=True),
    sa.Column('total_innings', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['selected_opponent'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_game_captain'), 'game', ['captain'], unique=False)
    op.create_index(op.f('ix_game_created_at'), 'game', ['created_at'], unique=False)
    op.create_index(op.f('ix_game_player_id'), 'game', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_admin'), 'player', ['admin'], unique=False)
    op.create_index(op.f('ix_player_division'), 'player', ['division'], unique=False)
    op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=True)
    op.create_index(op.f('ix_player_first_name'), 'player', ['first_name'], unique=False)
    op.create_index(op.f('ix_player_last_name'), 'player', ['last_name'], unique=False)
    op.create_index(op.f('ix_player_subscribed'), 'player', ['subscribed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_subscribed'), table_name='player')
    op.drop_index(op.f('ix_player_last_name'), table_name='player')
    op.drop_index(op.f('ix_player_first_name'), table_name='player')
    op.drop_index(op.f('ix_player_email'), table_name='player')
    op.drop_index(op.f('ix_player_division'), table_name='player')
    op.drop_index(op.f('ix_player_admin'), table_name='player')
    op.drop_index(op.f('ix_game_player_id'), table_name='game')
    op.drop_index(op.f('ix_game_created_at'), table_name='game')
    op.drop_index(op.f('ix_game_captain'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
