"""added game log table

Revision ID: cbecb99d2992
Revises: 959aef2eba67
Create Date: 2020-08-02 00:12:50.906939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbecb99d2992'
down_revision = '959aef2eba67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('loser_id', sa.Integer(), nullable=True),
    sa.Column('winning_score', sa.Integer(), nullable=True),
    sa.Column('losing_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_game_log_created_at'), 'game_log', ['created_at'], unique=False)
    op.add_column('game', sa.Column('opponent_id', sa.Integer(), nullable=True))
    op.drop_constraint('game_ibfk_2', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'player', ['opponent_id'], ['id'])
    op.drop_column('game', 'selected_opponent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('selected_opponent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_ibfk_2', 'game', 'player', ['selected_opponent'], ['id'])
    op.drop_column('game', 'opponent_id')
    op.drop_index(op.f('ix_game_log_created_at'), table_name='game_log')
    op.drop_table('game_log')
    # ### end Alembic commands ###
