"""added back some old fields

Revision ID: dcec842f1982
Revises: 17970bcb3ad4
Create Date: 2020-08-02 20:03:26.230462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcec842f1982'
down_revision = '17970bcb3ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('captain', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('game_won', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('loser_score', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('winner_score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_game_captain'), 'game', ['captain'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_captain'), table_name='game')
    op.drop_column('game', 'winner_score')
    op.drop_column('game', 'loser_score')
    op.drop_column('game', 'game_won')
    op.drop_column('game', 'captain')
    # ### end Alembic commands ###
