"""added captain option to player

Revision ID: f787674389f9
Revises: 8206a708eacd
Create Date: 2021-03-26 01:49:06.861633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f787674389f9'
down_revision = '8206a708eacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('captain', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_player_captain'), 'player', ['captain'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_captain'), table_name='player')
    op.drop_column('player', 'captain')
    # ### end Alembic commands ###
